name: Deploy

on:
  push:
    branches:
      - hw9_Deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      # - run: npm run test
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: shrouded-savannah-18182 #Must be unique in Heroku
          heroku_email: nova.ua@ukr.net
